#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: https://aste.date
baseurl: ""
title: TBZmang
description: Hello life. Goodbye life.
language: zh
avatar: /assets/img/icon.jpg
favicon: /assets/img/icon.jpg

theme: jekyll-theme-hacker
